#!/bin/bash
# combustion: network
SUSEConnect -r <LICENSE_KEY>  -e <SCC_EMAIL>

# Install extra packages
zypper -n install \
    tar \
    conmon \
    curl

# Install updates
## BEWARE: Updating SLE Micro during combustion might result in a new kernel being loaded with some kernel extensions necessary for K3S
## If you DO need to upgrade SLE Micro during Combustion, you need a reboot directly after the first boot for the modules to load correctly and K3S to start correctly.
# zypper -n up

# K3S Prep: Needed because /usr/local (which is the standard location for K3S is not mounted by default for this stage of Combustion)
mount /dev/disk/by-label/ROOT -o subvol=@/usr/local /usr/local
mount /dev/disk/by-label/ROOT -o subvol=@/var /var

# Install K3S
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -

umount /usr/local
umount /var